name: Build and push docker image

on:
  push:
    branches: [main]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image:${{ github.sha }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push the image to Docker Hub
      run: |
        docker tag my-image:${{ github.sha }} my-username/my-image:${{ github.sha }}
        docker push my-username/my-image:${{ github.sha }}
        docker tag my-image:${{ github.sha }} my-username/my-image:latest
        docker push my-username/my-image:latest