name: Build and push docker image

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Build the Docker image (x86_64)
      run: docker build . --file Dockerfile --tag jsilkens/awscli-kubectl:latest-amd64 --platform linux/amd64
      
    - name: Build the Docker image (ARM)
      run: docker build . --file Dockerfile --tag jsilkens/awscli-kubectl:latest-arm64 --platform linux/arm64
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push the x86_64 image
      run: docker push jsilkens/awscli-kubectl:latest-amd64
      
    - name: Push the ARM64 image
      run: docker push jsilkens/awscli-kubectl:latest-arm64
      
    - name: Create Docker manifest
      run: |
        docker manifest create jsilkens/awscli-kubectl:latest \
        --amend jsilkens/awscli-kubectl:latest-amd64 \
        --amend jsilkens/awscli-kubectl:latest-arm64
        
    - name: Push the manifest
      run: docker manifest push jsilkens/awscli-kubectl:latest